Revert "[requirements.txt] remove feaTools as no longer used"
This reverts commit d6af72c6b5ee1011487811b46ee2d39054df2059.

It turns out ufo2ft actually requires it...

Traceback (most recent call last):
  File "ufo2ft/Lib/ufo2ft/kernFeatureWriter.py", line 2, in <module>
    from feaTools import parser
ImportError: No module named 'feaTools'